// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhEKPfktjxZocQFdTCO0DECINwBsk60E0',
    appId: '1:335385716232:web:2215b2bf7d7bbbe8d3d3bd',
    messagingSenderId: '335385716232',
    projectId: 'pettag-d02f6',
    authDomain: 'pettag-d02f6.firebaseapp.com',
    storageBucket: 'pettag-d02f6.appspot.com',
    measurementId: 'G-1TDY1LR7N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9cEK52BndulA1jGMwcj1ehTgLmNKwsLU',
    appId: '1:335385716232:android:faa8ce08dd7c3d85d3d3bd',
    messagingSenderId: '335385716232',
    projectId: 'pettag-d02f6',
    storageBucket: 'pettag-d02f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9-pTpVPMU2wKnWvJQ6XnW7u2rkBOOuWk',
    appId: '1:335385716232:ios:92514e8087b00a9cd3d3bd',
    messagingSenderId: '335385716232',
    projectId: 'pettag-d02f6',
    storageBucket: 'pettag-d02f6.appspot.com',
    androidClientId: '335385716232-2npv47tk1s2ebe3498fd83oc3qfn5r2r.apps.googleusercontent.com',
    iosClientId: '335385716232-77itsrpm9b6m8rvedg8hfhrchqj1jm2t.apps.googleusercontent.com',
    iosBundleId: 'com.utechware.socialapppettag',
  );
}
